import type { Metadata } from "next";
import { Inter, Space_Mono, Orbitron } from "next/font/google";
import "./globals.css";
import CustomCursor from "@/components/CustomCursor";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const spaceMono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-space-mono"
});
const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron"
});

const SITE_URL = "https://bennygingi.tech";
const NAME = "Benny Gingihashvili";
const ROLE = "SOC Analyst & Full-Stack Developer";
const DESCRIPTION =
  "Portfolio of Benny Gingihashvili — SOC analyst and full-stack developer bridging offensive security and robust engineering.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: `${NAME} — ${ROLE}`,
  description: DESCRIPTION,
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    url: SITE_URL,
    siteName: NAME,
    title: `${NAME} — ${ROLE}`,
    description: DESCRIPTION,
    // og:image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: `${NAME} — ${ROLE}`,
    description: DESCRIPTION,
    // twitter:image is generated by app/twitter-image.tsx
  },
};

// JSON-LD Person schema — no employer claim (SOC role has concluded).
const personJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: NAME,
  url: SITE_URL,
  jobTitle: ROLE,
  sameAs: [
    "https://github.com/BennyGingi",
    "https://www.linkedin.com/in/benny-gingihasvili/",
  ],
  knowsAbout: [
    "Security Operations",
    "SIEM",
    "Incident Response",
    "Threat Detection",
    "Phishing Triage",
    "Full-Stack Development",
    "Next.js",
    "TypeScript",
    "Python",
  ],
};

import { ThemeProvider } from "next-themes";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${spaceMono.variable} ${orbitron.variable} antialiased`}
      >
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
        />
        <ThemeProvider attribute="data-theme" defaultTheme="dark" enableSystem={false}>
          <CustomCursor />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
